services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - keys:/app/keys
      - uploads:/app/uploads

  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_DB: ${POSTGRESDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  keys:
  uploads:
