openapi: 3.1.0
info:
  title: Darkify API
  description: API for authentication and user management.
  version: 1.0.0

security:
  - bearerAuth: []

servers:
  - url: http://localhost:3000/api

paths:
  /users/register:
    post:
      tags: [Auth]
      summary: Register new user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered
          $ref: '#/components/responses/SuccessTokens'
        '400':
          $ref: '#/components/responses/ValidationError'

  /users/login:
    post:
      tags: [Auth]
      summary: Login user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User authenticated
          $ref: '#/components/responses/SuccessTokens'
        '400':
          $ref: '#/components/responses/ValidationError'

  /users/refresh-token:
    post:
      tags: [Auth]
      summary: Issue new access token using refresh token

      responses:
        '200':
          description: Access token returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        '400':
          $ref: '#/components/responses/ValidationError'

  /users/me:
    get:
      tags: [User]
      summary: Get current user info

      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags: [User]
      summary: Update current user info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                visible_username:
                  type: string

      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreview'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
    delete:
      summary: Delete current user
      tags: [User]
      responses:
        '200':
          $ref: '#/components/responses/SuccessStatus'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/me/settings:
    get:
      tags: [User]
      summary: Get current user settings

      responses:
        '200':
          description: List of user settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags: [User]
      summary: Update current user settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettings'
      responses:
        '200':
          description: List of user settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/me/following:
    get:
      tags: [User]
      summary: Get users followed by current user

      responses:
        '200':
          description: List of following users
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  next:
                    type: ['integer', 'null']
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserPreview'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /users/{userId}:
    get:
      tags: [User]
      summary: Get user info by ID

      parameters:
        - $ref: '#/components/parameters/UserIdParameter'
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /users/follow/user/{userId}:
    post:
      tags: [User]
      summary: Follow specified user

      parameters:
        - $ref: '#/components/parameters/UserIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessStatus'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /users/unfollow/user/{userId}:
    post:
      tags: [User]
      summary: Unfollow specified user

      parameters:
        - $ref: '#/components/parameters/UserIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessStatus'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /users/follow/playlist/{playlistId}:
    post:
      tags: [User]
      summary: Follow specified playlist
      parameters:
        - $ref: '#/components/parameters/PlaylistIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessStatus'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /users/unfollow/playlist/{playlistId}:
    post:
      tags: [User]
      summary: Unfollow specified playlist

      parameters:
        - $ref: '#/components/parameters/PlaylistIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessStatus'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/me/avatar:
    get:
      tags: [User]
      summary: Get avatar url
      responses:
        '200':
          description: avatar url
          content:
            application/json:
              schema:
                type: object
                properties:
                  avatar_url:
                    type: string
                    format: uri-reference
    put:
      tags: [User]
      summary: Change avatar for current user
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                avatar:
                  type: string
                  format: binary
  /tracks/:
    post:
      tags: [Track]
      summary: Upload track
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostTrackRequest'
      responses:
        '200':
          $ref: '#/components/responses/TrackInfoResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /tracks/{trackId}:
    get:
      tags: [Track]
      summary: Get trackInfo by id
      parameters:
        - $ref: '#/components/parameters/TrackIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/TrackInfoResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags: [Track]
      summary: Update trackInfo by id
      parameters:
        - $ref: '#/components/parameters/TrackIdParameter'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PutTrackRequest'
      responses:
        '200':
          $ref: '#/components/responses/TrackInfoResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
    delete:
      summary: Delete track by id
      tags: [Track]
      responses:
        '200':
          $ref: '#/components/responses/SuccessStatus'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /tracks/search/{trackName}:
    get:
      summary: Get all tracks by trackName. Case insensitive
      tags: [Track]
      parameters:
        - $ref: '#/components/parameters/TrackNameParameter'
      responses:
        '200':
          description: array of trackInfo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackInfo'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /tracks/stream/{trackId}:
    get:
      summary: Get m3u8 file for streaming. Depends on user's chosen bitrate
      tags: [Track]
      parameters:
        - $ref: '#/components/parameters/TrackIdParameter'
      responses:
        '200':
          description: m3u8 playlist file
          content:
            application/vnd.apple.mpegurl:
              schema:
                type: string
                format: binary

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          $ref: '#/components/schemas/Password'
    Bitrate:
      description: User's bitrate option. Can be low, normal, high, veryHigh or auto.
      type: string
      enum: [low, normal, high, veryHigh, auto]
    LoginRequest:
      type: object
      required: [password]
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          $ref: '#/components/schemas/Password'

    AccessToken:
      type: object
      properties:
        accessToken:
          $ref: '#/components/schemas/Token'

    Token:
      type: object
      properties:
        token:
          type: string
        expires:
          type: string

    Password:
      type: string
      format: password
      minLength: 8
      maxLength: 20

    UserInfo:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        visible_username:
          type: string
        avatar_url:
          type: string
          format: uri-reference
        followers:
          type: integer
    UserSettings:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        bitrate:
          $ref: '#/components/schemas/Bitrate'
    UserPreview:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        visible_username:
          type: string
        avatar_url:
          type: string
          format: uri-reference
    TrackInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        admin_id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        artists:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              visible_username:
                type: string
        cover_url:
          type: string
          format: uri-reference
        lyrics?:
          type: [string, 'null']
        play_count:
          type: number
        deleted?:
          type: boolean
        duration:
          type: string
    PostTrackRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        cover:
          type: string
          format: binary
        track:
          type: string
          format: binary
        artists:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              visible_username:
                type: string
        lyrics?:
          type: [string, 'null']
    PutTrackRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        lyrics?:
          type: [string, 'null']
        artists:
          type: array
          items:
            type: string
            format: uuid
        cover:
          type: string
          format: binary
  parameters:
    UserIdParameter:
      in: path
      name: user_id
      required: true
      schema:
        type: string
        format: uuid

    PlaylistIdParameter:
      in: path
      name: playlist_id
      required: true
      schema:
        type: string
    TrackIdParameter:
      in: path
      name: trackId
      required: true
      schema:
        type: string
        format: uuid
    TrackNameParameter:
      in: path
      name: trackName
      required: true
      schema:
        type: string
        maxLength: 100

  responses:
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    Unauthorized:
      description: Unauthorized or invalid token
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    SuccessTokens:
      description: Successful response with both access and refresh tokens
      content:
        application/json:
          schema:
            description: access token
            $ref: '#/components/schemas/Token'
      headers:
        Set-Cookie:
          schema:
            description: refresh token
            $ref: '#/components/schemas/Token'

    SuccessStatus:
      description: Successful response with no data

    TrackInfoResponse:
      description: trackInfo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrackInfo'
