name: TypeScript

on:
  push:

jobs:
  ts-frontend:
    name: TS Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install frontend dependencies
        run: |
          cd web
          yarn install

      - name: Run TS for frontend
        run: |
          cd web
          yarn run test:typescript

  ts-backend:
    name: TS Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run TS for backend
        run: |
          cd backend
          npm run test:typescript